"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import AppLayout from "@/components/layout/AppLayout";
import { financeService } from "@/services/financeService";
import type { FinancialCategory, FinancialDirection, FinancialTransaction } from "@/types/finance";

const money = (n: number) => `₦${Number(n || 0).toLocaleString("en-NG", { maximumFractionDigits: 0 })}`;
const labels: Record<string, string> = { sales: "Sales", customer_payment: "Customer payment", engineer_payment: "Engineer payment", repair_payment: "Repair payment", part_purchase: "Part purchase", salary: "Salary", rent: "Rent", utility: "Utility", other: "Other" };

export default function FinancePage() {
  const [transactions, setTransactions] = useState<FinancialTransaction[]>([]); const [direction, setDirection] = useState<FinancialDirection>("out"); const [category, setCategory] = useState<FinancialCategory>("other"); const [amount, setAmount] = useState(""); const [method, setMethod] = useState("cash"); const [description, setDescription] = useState(""); const [period, setPeriod] = useState("month"); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  async function load() { const result = await financeService.getTransactions(); if (!result.error) setTransactions((result.data ?? []) as FinancialTransaction[]); else setMessage(result.error.message); }
  useEffect(() => { void load(); }, []);
  const filtered = useMemo(() => { if (period === "all") return transactions; const start = new Date(); start.setHours(0,0,0,0); if (period === "week") start.setDate(start.getDate() - 6); if (period === "month") start.setDate(1); return transactions.filter(t => new Date(t.occurred_at) >= start); }, [transactions, period]);
  const totals = filtered.reduce((a,t) => { const v = Number(t.amount); t.direction === "in" ? a.in += v : a.out += v; return a; }, { in: 0, out: 0 });
  async function submit(e: FormEvent) { e.preventDefault(); const value = Number(amount); if (!value || value <= 0 || !description.trim()) { setMessage("Enter an amount and description."); return; } setSaving(true); const result = await financeService.createTransaction({ direction, category, amount: value, payment_method: method, description }); if (result.error) setMessage(result.error.message); else { setAmount(""); setDescription(""); setMessage("Money movement recorded."); await load(); } setSaving(false); }

  return <AppLayout><main className="space-y-6">
    <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#1d6a54]">Owner money control</p><h1 className="mt-1 font-heading text-3xl font-bold tracking-tight text-[#182a28]">Credit & Money</h1><p className="mt-1 max-w-2xl text-sm leading-6 text-[#74837e]">Keep <strong>money Danchrista owes people</strong> separate from <strong>money people owe Danchrista</strong>. This page also records genuine cash movement and expenses.</p></div><Link href="/outstanding" className="inline-flex min-h-11 items-center justify-center rounded-xl bg-[#123b34] px-5 text-sm font-bold text-white">People who owe us</Link></header>
    <section className="grid gap-3 sm:grid-cols-3"><Card label="Money in" value={money(totals.in)} /><Card label="Money out" value={money(totals.out)} /><Card label="Net movement" value={money(totals.in - totals.out)} tone={totals.in - totals.out >= 0 ? "green" : "red"} /></section>
    <section className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]"><div className="space-y-5">
      <div className="grid gap-4 md:grid-cols-2"><div className="rounded-2xl border border-[#d7a95a]/35 bg-[#fffaf0] p-5"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#8a641d]">Credit book</p><h2 className="mt-1 font-heading text-lg font-bold text-[#182a28]">People Danchrista owes</h2><p className="mt-2 text-sm leading-6 text-[#6f6756]">The proper credit record should contain the person, phone, goods collected, amount owed, amount paid and due date. This stays separate from customer debit.</p><Link href="/finance" className="mt-4 inline-flex text-xs font-bold text-[#8a641d]">Manage money ledger →</Link></div><div className="rounded-2xl border border-[#dfe6df] bg-[#eef4f1] p-5"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#1d6a54]">Receivables</p><h2 className="mt-1 font-heading text-lg font-bold text-[#182a28]">People who owe us</h2><p className="mt-2 text-sm leading-6 text-[#285c4d]">Open the debit book to record daily collections, balances, phone numbers, WhatsApp reminders and statements.</p><Link href="/outstanding" className="mt-4 inline-flex text-xs font-bold text-[#1d6a54]">Open debit book →</Link></div></div>
      <section className="overflow-hidden rounded-2xl border border-[#dfe6df] bg-white"><div className="flex flex-col gap-3 border-b border-[#edf0ed] p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#1d6a54]">Cash book</p><h2 className="mt-1 font-heading text-lg font-bold text-[#182a28]">Money movement</h2></div><select value={period} onChange={e => setPeriod(e.target.value)} className="h-10 rounded-xl border border-[#dfe6df] bg-white px-3 text-sm"><option value="day">Today</option><option value="week">This week</option><option value="month">This month</option><option value="all">All time</option></select></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-[#f7f8f5]"><tr><th className="px-5 py-3 text-[10px] font-bold uppercase tracking-wide text-[#74837e]">Date</th><th className="px-5 py-3 text-[10px] font-bold uppercase tracking-wide text-[#74837e]">Description</th><th className="px-5 py-3 text-[10px] font-bold uppercase tracking-wide text-[#74837e]">Type</th><th className="px-5 py-3 text-[10px] font-bold uppercase tracking-wide text-[#74837e]">Method</th><th className="px-5 py-3 text-right text-[10px] font-bold uppercase tracking-wide text-[#74837e]">Amount</th></tr></thead><tbody>{filtered.map(t => <tr key={t.id} className="border-t border-[#edf0ed]"><td className="whitespace-nowrap px-5 py-4 text-xs text-[#74837e]">{new Date(t.occurred_at).toLocaleDateString("en-NG")}</td><td className="px-5 py-4 font-medium text-[#182a28]">{t.description}</td><td className="px-5 py-4 text-xs text-[#53635d]">{labels[t.category] ?? t.category}</td><td className="px-5 py-4 text-xs text-[#53635d]">{t.payment_method}</td><td className={`px-5 py-4 text-right font-bold ${t.direction === "in" ? "text-emerald-700" : "text-red-700"}`}>{t.direction === "in" ? "+" : "−"}{money(Number(t.amount))}</td></tr>)}</tbody></table>{filtered.length === 0 && <div className="py-12 text-center text-sm text-[#74837e]">No money movement in this period.</div>}</div></section>
    </div>
    <section className="rounded-2xl border border-[#dfe6df] bg-white p-5 shadow-[0_10px_28px_rgba(18,59,52,0.05)]"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#1d6a54]">Manual money entry</p><h2 className="mt-1 font-heading text-lg font-bold text-[#182a28]">Record movement</h2><p className="mt-1 text-xs leading-5 text-[#74837e]">Use this for genuine cash movements not already created by sales, repairs or payments.</p><form onSubmit={submit} className="mt-5 space-y-4"><label className="block text-xs font-bold text-[#53635d]">Direction<select value={direction} onChange={e => setDirection(e.target.value as FinancialDirection)} className="mt-1 h-11 w-full rounded-xl border border-[#dfe6df] bg-white px-3 text-sm font-normal"><option value="out">Money out</option><option value="in">Money in</option></select></label><label className="block text-xs font-bold text-[#53635d]">Category<select value={category} onChange={e => setCategory(e.target.value as FinancialCategory)} className="mt-1 h-11 w-full rounded-xl border border-[#dfe6df] bg-white px-3 text-sm font-normal"><option value="other">Other</option><option value="part_purchase">Part purchase</option><option value="salary">Salary</option><option value="rent">Rent</option><option value="utility">Utility</option></select></label><label className="block text-xs font-bold text-[#53635d]">Amount<input type="number" min="1" value={amount} onChange={e => setAmount(e.target.value)} className="mt-1 h-11 w-full rounded-xl border border-[#dfe6df] px-3 text-sm font-normal" placeholder="₦0" /></label><label className="block text-xs font-bold text-[#53635d]">Payment method<select value={method} onChange={e => setMethod(e.target.value)} className="mt-1 h-11 w-full rounded-xl border border-[#dfe6df] bg-white px-3 text-sm font-normal"><option value="cash">Cash</option><option value="transfer">Transfer</option><option value="pos">POS</option><option value="other">Other</option></select></label><label className="block text-xs font-bold text-[#53635d]">Description<input value={description} onChange={e => setDescription(e.target.value)} className="mt-1 h-11 w-full rounded-xl border border-[#dfe6df] px-3 text-sm font-normal" placeholder="e.g. electricity" /></label><button disabled={saving} className="h-11 w-full rounded-xl bg-[#123b34] text-sm font-bold text-white disabled:opacity-50">{saving ? "Saving..." : "Record movement"}</button></form>{message && <p className="mt-3 rounded-xl bg-[#f7f8f5] p-3 text-xs text-[#53635d]">{message}</p>}</section>
    </section>
  </main></AppLayout>;
}
function Card({ label, value, tone }: { label: string; value: string; tone?: "green" | "red" }) { return <div className="rounded-2xl border border-[#dfe6df] bg-white p-5 shadow-[0_8px_24px_rgba(18,59,52,0.05)]"><p className="text-xs font-semibold text-[#74837e]">{label}</p><p className={`mt-2 font-heading text-2xl font-bold ${tone === "green" ? "text-[#1d6a54]" : tone === "red" ? "text-red-700" : "text-[#182a28]"}`}>{value}</p></div>; }
