"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import AppLayout from "@/components/layout/AppLayout";
import { financeService } from "@/services/financeService";
import { businessOperationsService } from "@/services/businessOperationsService";
import type { FinancialCategory, FinancialDirection, FinancialTransaction } from "@/types/finance";

const money = (n: number) => `₦${Number(n || 0).toLocaleString("en-NG", { maximumFractionDigits: 0 })}`;
const labels: Record<string, string> = { sales: "Sales", customer_payment: "Customer payment", engineer_payment: "Engineer payment", repair_payment: "Repair payment", part_purchase: "Part purchase", salary: "Salary", rent: "Rent", utility: "Utility", other: "Other" };
type Payable = { id: string; person_name: string; phone: string | null; description: string | null; agreed_amount: number; amount_paid: number; balance: number; due_date: string | null; computed_status: string; created_at: string };

export default function FinancePage() {
  const [transactions, setTransactions] = useState<FinancialTransaction[]>([]);
  const [payables, setPayables] = useState<Payable[]>([]);
  const [direction, setDirection] = useState<FinancialDirection>("out");
  const [category, setCategory] = useState<FinancialCategory>("other");
  const [amount, setAmount] = useState(""); const [method, setMethod] = useState("cash"); const [description, setDescription] = useState(""); const [period, setPeriod] = useState("month");
  const [person, setPerson] = useState(""); const [phone, setPhone] = useState(""); const [goods, setGoods] = useState(""); const [owed, setOwed] = useState(""); const [dueDate, setDueDate] = useState("");
  const [selectedPayable, setSelectedPayable] = useState<Payable | null>(null); const [payAmount, setPayAmount] = useState(""); const [payMethod, setPayMethod] = useState("cash");
  const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");

  async function load() {
    const [moneyResult, payableResult] = await Promise.all([financeService.getTransactions(), businessOperationsService.getSupplierPayables()]);
    if (!moneyResult.error) setTransactions((moneyResult.data ?? []) as FinancialTransaction[]);
    if (!payableResult.error) setPayables((payableResult.data ?? []) as Payable[]); else setMessage(payableResult.error.message);
  }
  useEffect(() => { void load(); }, []);
  const filtered = useMemo(() => { if (period === "all") return transactions; const start = new Date(); start.setHours(0,0,0,0); if (period === "week") start.setDate(start.getDate() - 6); if (period === "month") start.setDate(1); return transactions.filter(t => new Date(t.occurred_at) >= start); }, [transactions, period]);
  const totals = filtered.reduce((a,t) => { const v = Number(t.amount); t.direction === "in" ? a.in += v : a.out += v; return a; }, { in: 0, out: 0 });
  const openPayables = payables.filter(p => p.computed_status !== "paid" && p.computed_status !== "cancelled");
  const totalOwed = openPayables.reduce((s,p) => s + Number(p.balance), 0);
  const dueSoon = openPayables.filter(p => p.due_date && new Date(p.due_date) <= new Date(Date.now() + 7*86400000));

  async function submitMoney(e: FormEvent) { e.preventDefault(); const value = Number(amount); if (!value || value <= 0 || !description.trim()) { setMessage("Enter an amount and description."); return; } setSaving(true); const result = await financeService.createTransaction({ direction, category, amount: value, payment_method: method, description }); setMessage(result.error ? result.error.message : "Money movement recorded."); if (!result.error) { setAmount(""); setDescription(""); await load(); } setSaving(false); }
  async function submitPayable(e: FormEvent) { e.preventDefault(); const value = Number(owed); if (!person.trim() || !goods.trim() || value <= 0) { setMessage("Enter the person's name, goods collected and amount owed."); return; } setSaving(true); const result = await businessOperationsService.createSupplierPayable({ personName: person, phone, description: goods, agreedAmount: value, dueDate: dueDate || null }); if (result.error || !result.data) { setMessage(result.error?.message ?? "Could not create credit record."); setSaving(false); return; } const item = await businessOperationsService.addSupplierPayableItem({ payableId: result.data.id, itemName: goods, quantity: 1, unitValue: value }); setMessage(item.error ? item.error.message : "Credit record saved — Danchrista now has a clear payable balance."); setPerson(""); setPhone(""); setGoods(""); setOwed(""); setDueDate(""); await load(); setSaving(false); }
  async function submitPayment(e: FormEvent) { e.preventDefault(); if (!selectedPayable) return; const value = Number(payAmount); if (value <= 0) { setMessage("Enter a payment amount."); return; } setSaving(true); const result = await businessOperationsService.recordSupplierPayablePayment({ payableId: selectedPayable.id, amount: value, paymentMethod: payMethod as "cash" | "transfer" | "pos" | "other" }); setMessage(result.error ? result.error.message : "Payment recorded and balance updated."); if (!result.error) { setPayAmount(""); setSelectedPayable(null); await load(); } setSaving(false); }

  return <AppLayout><main className="space-y-6">
    <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#1d6a54]">Owner money control</p><h1 className="mt-1 font-heading text-3xl font-bold tracking-tight text-[#182a28]">Credit & Money</h1><p className="mt-1 max-w-2xl text-sm leading-6 text-[#74837e]">Two different books live here: <strong>people who owe Danchrista</strong> and <strong>people Danchrista owes</strong>. Never mix them.</p></div><Link href="/outstanding" className="inline-flex min-h-11 items-center justify-center rounded-xl bg-[#123b34] px-5 text-sm font-bold text-white">People who owe us</Link></header>
    <section className="grid gap-3 sm:grid-cols-4"><Card label="We owe" value={money(totalOwed)} /><Card label="Due within 7 days" value={money(dueSoon.reduce((s,p)=>s+Number(p.balance),0))} tone="amber" /><Card label="Money in" value={money(totals.in)} /><Card label="Money out" value={money(totals.out)} tone="red" /></section>

    <section className="rounded-2xl border border-[#d7a95a]/35 bg-[#fffaf0] p-5"><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#8a641d]">Credit book — Danchrista owes them</p><h2 className="mt-1 font-heading text-xl font-bold text-[#182a28]">Goods collected from people</h2><p className="mt-1 text-sm text-[#6f6756]">Record who we collected from, what we collected, what we agreed to pay, how much is paid and when the rest is due.</p></div><span className="rounded-full bg-white px-3 py-1 text-xs font-bold text-[#8a641d]">Outstanding: {money(totalOwed)}</span></div>
      <form onSubmit={submitPayable} className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-6"><Field label="Person" value={person} onChange={setPerson} placeholder="Name"/><Field label="Phone / WhatsApp" value={phone} onChange={setPhone} placeholder="080..."/><Field label="Goods collected" value={goods} onChange={setGoods} placeholder="e.g. iPhone 11 screen"/><Field label="Agreed amount" value={owed} onChange={setOwed} placeholder="₦0" type="number"/><label className="text-xs font-bold text-[#53635d]">Due date<input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)} className="mt-1 h-11 w-full rounded-xl border border-[#dfe6df] bg-white px-3 text-sm font-normal"/></label><button disabled={saving} className="mt-5 h-11 rounded-xl bg-[#123b34] px-4 text-sm font-bold text-white disabled:opacity-50">{saving ? "Saving..." : "Record credit"}</button></form>
      <div className="mt-5 overflow-x-auto rounded-xl border border-[#eadfc7] bg-white"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-[#fffaf0]"><tr><th className="px-4 py-3">Person</th><th className="px-4 py-3">Goods</th><th className="px-4 py-3">Agreed</th><th className="px-4 py-3">Paid</th><th className="px-4 py-3">Balance</th><th className="px-4 py-3">Due</th><th className="px-4 py-3"></th></tr></thead><tbody>{payables.map(p=><tr key={p.id} className="border-t border-[#f0eadc]"><td className="px-4 py-3 font-bold text-[#182a28]">{p.person_name}<div className="text-[11px] font-normal text-[#8b918e]">{p.phone || "No number"}</div></td><td className="px-4 py-3 text-[#53635d]">{p.description || "—"}</td><td className="px-4 py-3">{money(Number(p.agreed_amount))}</td><td className="px-4 py-3 text-emerald-700">{money(Number(p.amount_paid))}</td><td className="px-4 py-3 font-bold text-red-700">{money(Number(p.balance))}</td><td className="px-4 py-3 text-xs">{p.due_date ? new Date(p.due_date).toLocaleDateString("en-NG") : "No date"}</td><td className="px-4 py-3"><button onClick={()=>setSelectedPayable(p)} className="rounded-lg border border-[#dfe6df] px-3 py-2 text-xs font-bold">Record payment</button></td></tr>)}</tbody></table>{payables.length===0&&<div className="py-10 text-center text-sm text-[#74837e]">No credit/payable records yet.</div>}</div>
    </section>

    {selectedPayable && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 p-4"><form onSubmit={submitPayment} className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#1d6a54]">Payment</p><h2 className="mt-1 text-xl font-bold text-[#182a28]">Pay {selectedPayable.person_name}</h2><p className="mt-1 text-sm text-[#74837e]">Outstanding: <strong>{money(Number(selectedPayable.balance))}</strong></p><input autoFocus type="number" min="1" max={selectedPayable.balance} value={payAmount} onChange={e=>setPayAmount(e.target.value)} placeholder="Amount" className="mt-5 h-11 w-full rounded-xl border border-[#dfe6df] px-3"/><select value={payMethod} onChange={e=>setPayMethod(e.target.value)} className="mt-3 h-11 w-full rounded-xl border border-[#dfe6df] bg-white px-3"><option value="cash">Cash</option><option value="transfer">Transfer</option><option value="pos">POS</option><option value="other">Other</option></select><div className="mt-5 flex gap-2"><button type="button" onClick={()=>setSelectedPayable(null)} className="h-11 flex-1 rounded-xl border border-[#dfe6df] font-bold">Cancel</button><button disabled={saving} className="h-11 flex-1 rounded-xl bg-[#123b34] text-white font-bold">Record payment</button></div></form></div>}

    <section className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]"><section className="overflow-hidden rounded-2xl border border-[#dfe6df] bg-white"><div className="flex flex-col gap-3 border-b border-[#edf0ed] p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#1d6a54]">Cash book</p><h2 className="mt-1 font-heading text-lg font-bold text-[#182a28]">Money movement</h2></div><select value={period} onChange={e => setPeriod(e.target.value)} className="h-10 rounded-xl border border-[#dfe6df] bg-white px-3 text-sm"><option value="day">Today</option><option value="week">This week</option><option value="month">This month</option><option value="all">All time</option></select></div><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="bg-[#f7f8f5]"><tr><th className="px-5 py-3 text-[10px] uppercase tracking-wide text-[#74837e]">Date</th><th className="px-5 py-3 text-[10px] uppercase tracking-wide text-[#74837e]">Description</th><th className="px-5 py-3 text-[10px] uppercase tracking-wide text-[#74837e]">Type</th><th className="px-5 py-3 text-right text-[10px] uppercase tracking-wide text-[#74837e]">Amount</th></tr></thead><tbody>{filtered.map(t=><tr key={t.id} className="border-t border-[#edf0ed]"><td className="px-5 py-4 text-xs text-[#74837e]">{new Date(t.occurred_at).toLocaleDateString("en-NG")}</td><td className="px-5 py-4 font-medium">{t.description}</td><td className="px-5 py-4 text-xs">{labels[t.category] ?? t.category}</td><td className={`px-5 py-4 text-right font-bold ${t.direction === "in" ? "text-emerald-700" : "text-red-700"}`}>{t.direction === "in" ? "+" : "−"}{money(Number(t.amount))}</td></tr>)}</tbody></table>{filtered.length===0&&<div className="py-10 text-center text-sm text-[#74837e]">No money movement in this period.</div>}</div></section>
    <section className="rounded-2xl border border-[#dfe6df] bg-white p-5"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#1d6a54]">Cash book entry</p><h2 className="mt-1 font-heading text-lg font-bold">Record movement</h2><form onSubmit={submitMoney} className="mt-5 space-y-4"><label className="block text-xs font-bold">Direction<select value={direction} onChange={e=>setDirection(e.target.value as FinancialDirection)} className="mt-1 h-11 w-full rounded-xl border px-3"><option value="out">Money out</option><option value="in">Money in</option></select></label><label className="block text-xs font-bold">Category<select value={category} onChange={e=>setCategory(e.target.value as FinancialCategory)} className="mt-1 h-11 w-full rounded-xl border px-3"><option value="other">Other</option><option value="part_purchase">Part purchase</option><option value="salary">Salary</option><option value="rent">Rent</option><option value="utility">Utility</option></select></label><Field label="Amount" value={amount} onChange={setAmount} placeholder="₦0" type="number"/><label className="block text-xs font-bold">Payment method<select value={method} onChange={e=>setMethod(e.target.value)} className="mt-1 h-11 w-full rounded-xl border px-3"><option value="cash">Cash</option><option value="transfer">Transfer</option><option value="pos">POS</option><option value="other">Other</option></select></label><Field label="Description" value={description} onChange={setDescription} placeholder="e.g. electricity"/><button disabled={saving} className="h-11 w-full rounded-xl bg-[#123b34] text-sm font-bold text-white disabled:opacity-50">{saving?"Saving...":"Record movement"}</button></form>{message&&<p className="mt-3 rounded-xl bg-[#f7f8f5] p-3 text-xs text-[#53635d]">{message}</p>}</section></section>
  </main></AppLayout>;
}
function Field({label,value,onChange,placeholder,type="text"}:{label:string;value:string;onChange:(v:string)=>void;placeholder:string;type?:string}) { return <label className="block text-xs font-bold text-[#53635d]">{label}<input type={type} min={type==="number"?"0.01":undefined} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="mt-1 h-11 w-full rounded-xl border border-[#dfe6df] bg-white px-3 text-sm font-normal"/></label>; }
function Card({label,value,tone}:{label:string;value:string;tone?:"red"|"amber"}) { return <div className="rounded-2xl border border-[#dfe6df] bg-white p-5"><p className="text-xs font-semibold text-[#74837e]">{label}</p><p className={`mt-2 font-heading text-2xl font-bold ${tone==="red"?"text-red-700":tone==="amber"?"text-[#8a641d]":"text-[#182a28]"}`}>{value}</p></div>; }
