"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import AppLayout from "@/components/layout/AppLayout";
import InventoryForm from "@/components/inventory/InventoryForm";
import InventoryTable from "@/components/inventory/InventoryTable";
import ReceiveStockPanel from "@/components/inventory/ReceiveStockPanel";
import TransferStockPanel from "@/components/inventory/TransferStockPanel";
import PurchaseStockPanel from "@/components/inventory/PurchaseStockPanel";
import { inventoryService } from "@/services/inventoryService";
import type { InventoryItem } from "@/types/inventory";

const PART_SUBCATEGORIES = ["Displays", "Charging", "Power", "Audio", "Back Glass / Housing", "Camera", "Other Phone Parts"];
const GOODS_SUBCATEGORIES = ["Chargers", "Cables", "Earphones", "Headsets", "Power Banks", "Speakers", "Phone Accessories", "Other Gadgets & Accessories"];
function groupFor(item: InventoryItem) { return item.item_type === "part" || item.category === "Phone Parts" ? "parts" : "goods"; }
function stockState(item: InventoryItem) { if (item.quantity === 0) return "out"; if (item.quantity <= item.minimum_stock) return "low"; return "in"; }
function money(n: number) { return `₦${Number(n || 0).toLocaleString("en-NG", { maximumFractionDigits: 0 })}`; }

export default function InventoryPage() {
  const [refreshKey, setRefreshKey] = useState(0), [editingItem, setEditingItem] = useState<InventoryItem | null>(null), [items, setItems] = useState<InventoryItem[]>([]), [query, setQuery] = useState(""), [group, setGroup] = useState<"all" | "parts" | "goods">("all"), [subcategory, setSubcategory] = useState("all"), [stockFilter, setStockFilter] = useState<"all" | "in" | "low" | "out">("all");
  useEffect(() => { inventoryService.getInventory().then(({ data, error }) => { if (!error) setItems((data || []) as InventoryItem[]); }); }, [refreshKey]);
  const subcategories = useMemo(() => group === "parts" ? PART_SUBCATEGORIES : group === "goods" ? GOODS_SUBCATEGORIES : [...new Set(items.map(i => i.subcategory).filter(Boolean) as string[])].sort(), [group, items]);
  const filtered = useMemo(() => { const needle = query.trim().toLowerCase(); return items.filter(item => { const itemGroup = groupFor(item); const text = `${item.item_name} ${item.brand || ""} ${item.compatible_models || ""} ${item.sku || ""} ${item.subcategory || ""} ${item.shelf_location || ""}`.toLowerCase(); return (!needle || text.includes(needle)) && (group === "all" || itemGroup === group) && (subcategory === "all" || item.subcategory === subcategory) && (stockFilter === "all" || stockState(item) === stockFilter); }); }, [items, query, group, subcategory, stockFilter]);
  const parts = items.filter(i => groupFor(i) === "parts"), goods = items.filter(i => groupFor(i) === "goods"), low = items.filter(i => stockState(i) === "low"), out = items.filter(i => stockState(i) === "out");
  const stockValue = items.reduce((sum, i) => sum + Number(i.quantity || 0) * Number(i.cost_price || 0), 0);
  const fastCandidates = [...items].sort((a, b) => Number(a.quantity) - Number(b.quantity)).slice(0, 5);
  const saveRefresh = () => setRefreshKey(v => v + 1);
  function changeGroup(value: "all" | "parts" | "goods") { setGroup(value); setSubcategory("all"); }

  return <AppLayout><main className="mx-auto w-full max-w-[1500px] space-y-6 p-4 sm:p-6 lg:p-8">
    <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#1d6a54]">Shop stockroom</p><h1 className="mt-1 font-heading text-3xl font-bold tracking-tight text-[#182a28]">Inventory</h1><p className="mt-1 max-w-2xl text-sm leading-6 text-[#74837e]">Browse stock like a catalogue: accessories separate from phone parts, with stock warnings and clear selling prices.</p></div><div className="flex flex-wrap gap-2"><Link href="/inventory/import" className="inline-flex min-h-10 items-center rounded-xl bg-[#123b34] px-4 text-sm font-bold text-white">Import catalogue</Link><Link href="/inventory/movements" className="inline-flex min-h-10 items-center rounded-xl border border-[#dfe6df] bg-white px-4 text-sm font-semibold text-[#394b45]">Stock history</Link></div></header>

    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><StockCard title="Accessories" value={goods.length} detail="Chargers, cables, gadgets" onClick={() => changeGroup("goods")} /><StockCard title="Phone parts" value={parts.length} detail="Downboards, flexes, glass" onClick={() => changeGroup("parts")} /><StockCard title="Low stock" value={low.length} detail="At reorder level" tone="amber" onClick={() => setStockFilter("low")} /><StockCard title="Out of stock" value={out.length} detail="Needs attention now" tone="red" onClick={() => setStockFilter("out")} /><div className="rounded-2xl border border-[#dfe6df] bg-[#123b34] p-4 text-white shadow-[0_10px_28px_rgba(18,59,52,0.08)]"><p className="text-[10px] font-bold uppercase tracking-[0.15em] text-[#d7a95a]">Stock at cost</p><p className="mt-2 font-heading text-xl font-bold">{money(stockValue)}</p><p className="mt-1 text-[11px] text-[#c7d8d2]">What is currently sitting in the shop</p></div></section>

    <section className="grid gap-5 lg:grid-cols-[1fr_330px]"><div className="rounded-2xl border border-[#dfe6df] bg-white p-4 shadow-[0_10px_28px_rgba(18,59,52,0.05)]"><div className="flex flex-col gap-3 lg:flex-row"><input aria-label="Search inventory" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search product, model, brand, SKU or shelf..." className="h-11 min-w-0 flex-1 rounded-xl border border-[#dfe6df] px-3 text-sm outline-none focus:border-[#1d6a54] focus:ring-2 focus:ring-[#1d6a54]/10" /><select aria-label="Inventory group" value={group} onChange={e => changeGroup(e.target.value as typeof group)} className="h-11 rounded-xl border border-[#dfe6df] bg-white px-3 text-sm"><option value="all">Everything</option><option value="goods">Accessories & gadgets</option><option value="parts">Phone parts</option></select><select aria-label="Inventory subcategory" value={subcategory} onChange={e => setSubcategory(e.target.value)} className="h-11 rounded-xl border border-[#dfe6df] bg-white px-3 text-sm"><option value="all">All categories</option>{subcategories.map(value => <option key={value} value={value}>{value}</option>)}</select><select aria-label="Inventory stock status" value={stockFilter} onChange={e => setStockFilter(e.target.value as typeof stockFilter)} className="h-11 rounded-xl border border-[#dfe6df] bg-white px-3 text-sm"><option value="all">All stock</option><option value="in">Available</option><option value="low">Low</option><option value="out">Empty</option></select></div><div className="mt-3 flex flex-wrap items-center gap-4 text-xs text-[#74837e]"><span><strong className="text-[#182a28]">{filtered.length}</strong> products shown</span><span><strong className="text-[#182a28]">{items.length}</strong> total products</span>{(query || group !== "all" || subcategory !== "all" || stockFilter !== "all") && <button type="button" onClick={() => { setQuery(""); setGroup("all"); setSubcategory("all"); setStockFilter("all"); }} className="font-bold text-[#1d6a54]">Clear</button>}</div></div>
      <div className="rounded-2xl border border-[#e8e4da] bg-[#fbfaf7] p-4"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#8a641d]">Owner signal</p><h2 className="mt-1 font-heading text-base font-bold text-[#182a28]">Watch these items</h2><p className="mt-1 text-xs text-[#74837e]">The system already knows what is low. Fast-moving analysis can be layered on top of sales history.</p><div className="mt-3 space-y-2">{fastCandidates.map(item => <div key={item.id} className="flex items-center justify-between rounded-xl bg-white px-3 py-2 text-xs"><span className="truncate pr-2 font-medium text-[#394b45]">{item.item_name}</span><span className={stockState(item) === "low" || stockState(item) === "out" ? "font-bold text-amber-700" : "text-[#74837e]"}>{item.quantity} left</span></div>)}</div></div></section>

    <section className="grid gap-6 xl:grid-cols-4"><InventoryForm editingItem={editingItem} onSaved={() => { setEditingItem(null); saveRefresh(); }} onCancelEdit={() => setEditingItem(null)} /><ReceiveStockPanel refreshKey={refreshKey} onReceived={saveRefresh} /><PurchaseStockPanel items={items} onSaved={saveRefresh} /><TransferStockPanel items={items} onTransferred={saveRefresh} /></section>

    <section className="overflow-hidden rounded-2xl border border-[#dfe6df] bg-white shadow-[0_10px_28px_rgba(18,59,52,0.06)]"><div className="border-b border-[#edf0ed] px-5 py-4"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#1d6a54]">Catalogue</p><h2 className="mt-1 font-heading text-lg font-bold text-[#182a28]">Stock on hand</h2><p className="mt-1 text-xs text-[#74837e]">Selling price, quantity, category and stock threshold stay visible here.</p></div><InventoryTable refreshKey={refreshKey} onEdit={setEditingItem} itemsOverride={filtered} embedded /></section>
  </main></AppLayout>;
}

function StockCard({ title, value, detail, tone, onClick }: { title: string; value: number; detail: string; tone?: "amber" | "red"; onClick: () => void }) { const cls = tone === "red" ? "text-red-700 bg-red-50" : tone === "amber" ? "text-amber-700 bg-amber-50" : "text-[#1d6a54] bg-[#eef4f1]"; return <button onClick={onClick} className="rounded-2xl border border-[#dfe6df] bg-white p-4 text-left shadow-[0_8px_24px_rgba(18,59,52,0.05)] transition hover:-translate-y-0.5 hover:border-[#1d6a54]/25"><span className={`inline-flex rounded-lg px-2 py-1 text-[10px] font-bold uppercase tracking-wide ${cls}`}>{title}</span><p className="mt-3 font-heading text-2xl font-bold text-[#182a28]">{value}</p><p className="mt-1 text-[11px] text-[#74837e]">{detail}</p></button>; }
