"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import AppLayout from "@/components/layout/AppLayout";
import InventoryForm from "@/components/inventory/InventoryForm";
import InventoryTable from "@/components/inventory/InventoryTable";
import PurchaseStockPanel from "@/components/inventory/PurchaseStockPanel";
import { inventoryService } from "@/services/inventoryService";
import type { InventoryItem } from "@/types/inventory";

const PART_CATEGORIES = ["Downboards", "Charging Flex", "Power Flex", "Earpiece Flex", "Back Glass", "Other Phone Parts"];
const ACCESSORY_CATEGORIES = ["Chargers", "Cables", "Earphones", "Headsets", "Power Banks", "Speakers", "Phone Accessories", "Other Gadgets & Accessories"];
function groupFor(item: InventoryItem) { return item.item_type === "part" || item.category === "Phone Parts" ? "parts" : "accessories"; }
function stockState(item: InventoryItem) { if (Number(item.quantity) === 0) return "out"; if (Number(item.quantity) <= Number(item.minimum_stock)) return "low"; return "ok"; }
function money(n: number) { return `₦${Number(n || 0).toLocaleString("en-NG", { maximumFractionDigits: 0 })}`; }

export default function InventoryPage() {
  const [refreshKey, setRefreshKey] = useState(0); const [editingItem, setEditingItem] = useState<InventoryItem | null>(null); const [items, setItems] = useState<InventoryItem[]>([]); const [query, setQuery] = useState(""); const [group, setGroup] = useState<"all" | "accessories" | "parts">("all"); const [category, setCategory] = useState("all"); const [stockFilter, setStockFilter] = useState<"all" | "ok" | "low" | "out">("all");
  useEffect(() => { inventoryService.getInventory().then(({ data, error }) => { if (!error) setItems((data || []) as InventoryItem[]); }); }, [refreshKey]);
  const categories = useMemo(() => group === "parts" ? PART_CATEGORIES : group === "accessories" ? ACCESSORY_CATEGORIES : [...new Set(items.map(i => i.subcategory || i.category).filter(Boolean) as string[])].sort(), [group, items]);
  const filtered = useMemo(() => { const needle = query.trim().toLowerCase(); return items.filter(item => { const text = `${item.item_name} ${item.brand || ""} ${item.compatible_models || ""} ${item.sku || ""} ${item.subcategory || ""} ${item.category || ""}`.toLowerCase(); return (!needle || text.includes(needle)) && (group === "all" || groupFor(item) === group) && (category === "all" || item.subcategory === category || item.category === category) && (stockFilter === "all" || stockState(item) === stockFilter); }); }, [items, query, group, category, stockFilter]);
  const accessories = items.filter(i => groupFor(i) === "accessories"), parts = items.filter(i => groupFor(i) === "parts"), low = items.filter(i => stockState(i) === "low"), out = items.filter(i => stockState(i) === "out");
  const stockValue = items.reduce((sum, i) => sum + Number(i.quantity || 0) * Number(i.cost_price || 0), 0);
  function changeGroup(value: typeof group) { setGroup(value); setCategory("all"); }
  const refresh = () => setRefreshKey(v => v + 1);

  return <AppLayout><main className="mx-auto w-full max-w-[1500px] space-y-6 p-4 sm:p-6 lg:p-8">
    <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#1d6a54]">Shop catalogue</p><h1 className="mt-1 font-heading text-3xl font-bold tracking-tight text-[#182a28]">Inventory</h1><p className="mt-1 max-w-2xl text-sm leading-6 text-[#74837e]">Two clear shelves: <strong>Accessories</strong> and <strong>Phone Parts</strong>. Phone parts are separated by type, while brand/model identifies the exact part. Quantity, price floor and stock level stay with each item.</p></div><div className="flex flex-wrap gap-2"><Link href="/inventory/import" className="inline-flex min-h-10 items-center rounded-xl bg-[#123b34] px-4 text-sm font-bold text-white">Import items</Link><Link href="/inventory/movements" className="inline-flex min-h-10 items-center rounded-xl border border-[#dfe6df] bg-white px-4 text-sm font-semibold text-[#394b45]">Stock history</Link></div></header>

    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><StockCard title="Accessories" value={accessories.length} detail="Everyday shop goods" active={group === "accessories"} onClick={() => changeGroup("accessories")} /><StockCard title="Phone parts" value={parts.length} detail="Downboards, charging/power/earpiece flexes, back glass" active={group === "parts"} onClick={() => changeGroup("parts")} /><StockCard title="Low stock" value={low.length} detail="At or below reorder level" tone="amber" onClick={() => { setStockFilter("low"); setCategory("all"); }} /><StockCard title="Out of stock" value={out.length} detail="Needs owner attention" tone="red" onClick={() => { setStockFilter("out"); setCategory("all"); }} /><div className="rounded-2xl border border-[#dfe6df] bg-[#123b34] p-4 text-white"><p className="text-[10px] font-bold uppercase tracking-[0.15em] text-[#d7a95a]">Stock at cost</p><p className="mt-2 font-heading text-xl font-bold">{money(stockValue)}</p><p className="mt-1 text-[11px] text-[#c7d8d2]">Current stock value</p></div></section>
    <section className="rounded-2xl border border-[#dfe6df] bg-white p-5 shadow-[0_10px_28px_rgba(18,59,52,0.05)]">
      <div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between">
        <div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#1d6a54]">Stock shelves</p><h2 className="mt-1 font-heading text-xl font-bold text-[#182a28]">Find a part by category</h2><p className="mt-1 text-sm text-[#74837e]">Everything stays on this page. Pick a shelf, then a part type, then search by brand or model.</p></div>
        {(group !== "all" || category !== "all" || stockFilter !== "all") && <button type="button" onClick={() => { changeGroup("all"); setCategory("all"); setStockFilter("all"); }} className="text-xs font-bold text-[#1d6a54]">Reset shelf</button>}
      </div>
      <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">
        <CategoryCard label="All stock" count={items.length} active={group === "all" && category === "all"} onClick={() => { changeGroup("all"); setCategory("all"); }} />
        <CategoryCard label="Downboards" count={items.filter(i => groupFor(i) === "parts" && i.subcategory === "Downboards").length} active={category === "Downboards"} onClick={() => { changeGroup("parts"); setCategory("Downboards"); }} />
        <CategoryCard label="Charging Flex" count={items.filter(i => groupFor(i) === "parts" && i.subcategory === "Charging Flex").length} active={category === "Charging Flex"} onClick={() => { changeGroup("parts"); setCategory("Charging Flex"); }} />
        <CategoryCard label="Power Flex" count={items.filter(i => groupFor(i) === "parts" && i.subcategory === "Power Flex").length} active={category === "Power Flex"} onClick={() => { changeGroup("parts"); setCategory("Power Flex"); }} />
        <CategoryCard label="Earpiece Flex" count={items.filter(i => groupFor(i) === "parts" && i.subcategory === "Earpiece Flex").length} active={category === "Earpiece Flex"} onClick={() => { changeGroup("parts"); setCategory("Earpiece Flex"); }} />
        <CategoryCard label="Back Glass" count={items.filter(i => groupFor(i) === "parts" && i.subcategory === "Back Glass").length} active={category === "Back Glass"} onClick={() => { changeGroup("parts"); setCategory("Back Glass"); }} />
      </div>
      {group === "parts" && category !== "all" && <BrandShelf items={filtered} />}
      {group === "parts" && category === "all" && <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5">{["Tecno","Infinix","itel","Samsung","Redmi","Huawei","Nokia","iPhone","Other"].map(brand => <CategoryCard key={brand} label={brand} count={parts.filter(i => (i.brand || "").toLowerCase() === brand.toLowerCase()).length} active={false} onClick={() => setQuery(brand)} />)}</div>}
    </section>

    <section className="rounded-2xl border border-[#dfe6df] bg-white p-4 shadow-[0_10px_28px_rgba(18,59,52,0.05)]"><div className="grid gap-3 lg:grid-cols-[1fr_190px_220px_170px]"><input aria-label="Search inventory" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search product, model, brand or SKU..." className="h-11 rounded-xl border border-[#dfe6df] px-3 text-sm outline-none focus:border-[#1d6a54] focus:ring-2 focus:ring-[#1d6a54]/10" /><select aria-label="Shelf" value={group} onChange={e => changeGroup(e.target.value as typeof group)} className="h-11 rounded-xl border border-[#dfe6df] bg-white px-3 text-sm"><option value="all">All shelves</option><option value="accessories">Accessories</option><option value="parts">Phone Parts</option></select><select aria-label="Category" value={category} onChange={e => setCategory(e.target.value)} className="h-11 rounded-xl border border-[#dfe6df] bg-white px-3 text-sm"><option value="all">All categories</option>{categories.map(value => <option key={value} value={value}>{value}</option>)}</select><select aria-label="Stock status" value={stockFilter} onChange={e => setStockFilter(e.target.value as typeof stockFilter)} className="h-11 rounded-xl border border-[#dfe6df] bg-white px-3 text-sm"><option value="all">All stock</option><option value="ok">Healthy</option><option value="low">Low</option><option value="out">Empty</option></select></div><div className="mt-3 flex flex-wrap gap-4 text-xs text-[#74837e]"><span><strong className="text-[#182a28]">{filtered.length}</strong> shown</span><span><strong className="text-[#182a28]">{items.length}</strong> total items</span>{(query || group !== "all" || category !== "all" || stockFilter !== "all") && <button type="button" onClick={() => { setQuery(""); changeGroup("all"); setStockFilter("all"); }} className="font-bold text-[#1d6a54]">Clear filters</button>}</div></section>

    <section className="grid gap-4 lg:grid-cols-3"><Signal title="LOW STOCK" tone="amber" items={low.slice(0, 5)} empty="Nothing is at the reorder level." /><Signal title="OUT OF STOCK" tone="red" items={out.slice(0, 5)} empty="No empty items." /><div className="rounded-2xl border border-[#e8e4da] bg-[#fbfaf7] p-5"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#8a641d]">Owner control</p><h2 className="mt-1 font-heading text-base font-bold text-[#182a28]">Stock should tell you what to do</h2><p className="mt-2 text-sm leading-6 text-[#6f6756]">Reorder when stock reaches the threshold. Edit the selling price and floor when the market changes. Use Stock history for every adjustment, sale, repair use or return.</p></div></section>

    <section className="grid gap-6 xl:grid-cols-2"><InventoryForm editingItem={editingItem} onSaved={() => { setEditingItem(null); refresh(); }} onCancelEdit={() => setEditingItem(null)} /><PurchaseStockPanel items={items} onSaved={refresh} /></section>
    <section className="overflow-hidden rounded-2xl border border-[#dfe6df] bg-white shadow-[0_10px_28px_rgba(18,59,52,0.06)]"><div className="border-b border-[#edf0ed] px-5 py-4"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#1d6a54]">Products</p><h2 className="mt-1 font-heading text-lg font-bold text-[#182a28]">Shop stock</h2></div><InventoryTable refreshKey={refreshKey} onEdit={setEditingItem} itemsOverride={filtered} embedded /></section>
  </main></AppLayout>;
}

function StockCard({ title, value, detail, tone, active, onClick }: { title: string; value: number; detail: string; tone?: "amber" | "red"; active?: boolean; onClick: () => void }) { const cls = tone === "red" ? "text-red-700 bg-red-50" : tone === "amber" ? "text-amber-700 bg-amber-50" : "text-[#1d6a54] bg-[#eef4f1]"; return <button onClick={onClick} className={`rounded-2xl border p-4 text-left shadow-[0_8px_24px_rgba(18,59,52,0.05)] transition hover:-translate-y-0.5 ${active ? "border-[#1d6a54] ring-2 ring-[#1d6a54]/10" : "border-[#dfe6df] bg-white"}`}><span className={`inline-flex rounded-lg px-2 py-1 text-[10px] font-bold uppercase tracking-wide ${cls}`}>{title}</span><p className="mt-3 font-heading text-2xl font-bold text-[#182a28]">{value}</p><p className="mt-1 text-[11px] text-[#74837e]">{detail}</p></button>; }
function CategoryCard({ label, count, active, onClick }: { label: string; count: number; active: boolean; onClick: () => void }) { return <button type="button" onClick={onClick} className={`rounded-2xl border p-4 text-left transition hover:-translate-y-0.5 hover:border-[#1d6a54] hover:shadow-sm ${active ? "border-[#1d6a54] bg-[#eef4f1] ring-2 ring-[#1d6a54]/10" : "border-[#e4e9e5] bg-[#fbfcfa]"}`}><p className="text-sm font-bold text-[#182a28]">{label}</p><p className="mt-1 text-xs text-[#74837e]">{count} {count === 1 ? "item" : "items"}</p></button>; }
function BrandShelf({ items }: { items: InventoryItem[] }) { const brands = [...new Set(items.map(i => i.brand).filter(Boolean) as string[])].sort(); return <div className="mt-4 rounded-xl border border-[#edf0ed] bg-[#fbfcfa] p-4"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#74837e]">Brands in this shelf</p><div className="mt-3 flex flex-wrap gap-2">{brands.length ? brands.map(brand => <span key={brand} className="rounded-full bg-white px-3 py-1.5 text-xs font-semibold text-[#394b45] ring-1 ring-[#e4e9e5]">{brand}</span>) : <span className="text-xs text-[#74837e]">Add a brand when entering stock to build this shelf automatically.</span>}</div></div>; }
function Signal({ title, tone, items, empty }: { title: string; tone: "amber" | "red"; items: InventoryItem[]; empty: string }) { return <div className="rounded-2xl border border-[#dfe6df] bg-white p-5"><p className={`text-[10px] font-bold tracking-[0.16em] ${tone === "red" ? "text-red-700" : "text-amber-700"}`}>{title}</p><div className="mt-3 space-y-2">{items.length ? items.map(item => <div key={item.id} className="flex items-center justify-between gap-3 rounded-xl bg-[#f7f8f5] px-3 py-2.5"><span className="truncate text-sm font-semibold text-[#394b45]">{item.item_name}</span><span className={`shrink-0 text-xs font-bold ${tone === "red" ? "text-red-700" : "text-amber-700"}`}>{item.quantity} left</span></div>) : <p className="text-sm text-[#74837e]">{empty}</p>}</div></div>; }
