"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import AppLayout from "@/components/layout/AppLayout";
import { financeService } from "@/services/financeService";
import { dashboardService, type DashboardSummary } from "@/services/dashboardService";
import type { FinancialSummary, ProfitSummary } from "@/types/finance";

const money=(n:number)=>`₦${Number(n||0).toLocaleString("en-NG",{maximumFractionDigits:0})}`;
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};

export default function DailyClosingPage(){
 const [summary,setSummary]=useState<FinancialSummary|null>(null),[profit,setProfit]=useState<ProfitSummary|null>(null),[dash,setDash]=useState<DashboardSummary|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{void load()},[]);
 async function load(){setLoading(true);setError("");const day=today();const end=new Date(`${day}T23:59:59`).toISOString();const [s,p,d]=await Promise.all([financeService.getSummary(`${day}T00:00:00`,end),financeService.getProfitSummary(`${day}T00:00:00`,end),dashboardService.getSummary()]);if(s.error)setError(s.error.message);else setSummary(Array.isArray(s.data)?s.data[0]??null:null);if(p.error)setError(v=>v||p.error.message);else setProfit(Array.isArray(p.data)?p.data[0]??null:null);if(d.error){setError(v=>v||d.error?.message||"Unable to load dashboard summary")}else setDash(d.data);setLoading(false)}
 const rows=[['Money received',money(Number(summary?.total_in||0)),'Actual ledger inflow'],['Money out',money(Number(summary?.total_out||0)),'Recorded outflow'],['Net movement',money(Number(summary?.net_movement||0)),'Money in minus money out'],['Revenue',money(Number(profit?.total_revenue||0)),'Sales and repair revenue'],['Parts cost',money(Number(profit?.parts_cost||0)),'Cost of parts used'],['Operating expenses',money(Number(profit?.operating_expenses||0)),'Recorded operating costs'],['Engineer cost',money(Number(profit?.engineer_cost||0)),'Engineer-related cost'],['Net profit',money(Number(profit?.net_profit||0)),'Revenue minus recorded costs'],['Engineer debt',money(Number(dash?.engineer_debit||profit?.engineer_outstanding||0)),'Still owed by engineers'],['Customer debt',money(Number(dash?.outstanding_customer||profit?.outstanding_customer||0)),'Still owed by customers']];
 return <AppLayout><div className="space-y-6"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-teal-600">End of day</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-950">Daily Closing</h1><p className="mt-1 text-sm text-slate-500">Check what came in, went out, was earned and is still owed.</p></div><div className="flex gap-2"><Link href="/finance" className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700">Open ledger</Link><button onClick={()=>window.print()} className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">Print closing</button></div></header>{error&&<div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}{loading?<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[1,2,3].map(i=><div key={i} className="h-28 animate-pulse rounded-2xl bg-slate-100"/>)}</div>:<><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{rows.map(([label,value,hint])=><div key={label} className={`rounded-2xl border bg-white p-5 shadow-sm ${label==='Net profit'&&Number(profit?.net_profit||0)<0?'border-red-200':'border-slate-200'}`}><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">{label}</p><p className={`mt-2 text-2xl font-bold ${label==='Net profit'&&Number(profit?.net_profit||0)<0?'text-red-700':'text-slate-950'}`}>{value}</p><p className="mt-1 text-xs text-slate-500">{hint}</p></div>)}</section><section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-5"><h2 className="font-semibold text-slate-950">Closing checklist</h2><p className="mt-1 text-sm text-slate-500">Reconcile these before the shop closes.</p></div><div className="divide-y divide-slate-100">{[['New repairs',String(dash?.repairs_today??0)],['Completed repairs',String(dash?.completed_today??0)],['Cash recorded today',money(Number(dash?.cash_today||0))],['Low-stock items',String(dash?.low_stock_count??0)]].map(([a,b])=><div key={a} className="flex items-center justify-between px-5 py-4 text-sm"><span className="text-slate-600">{a}</span><strong className="text-slate-950">{b}</strong></div>)}</div></section></>}</div></AppLayout>
}
