"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { HandCoins, MessageCircle, Plus, Search, X } from "lucide-react";
import AppLayout from "@/components/layout/AppLayout";
import { businessOperationsService } from "@/services/businessOperationsService";
import { customerService } from "@/services/customerService";
import { customerBalanceMessage, openWhatsApp } from "@/lib/whatsapp";
import { toast } from "sonner";

type Balance = { customer_id: string; customer_name: string; phone: string; debit: number; credit: number; balance: number };
const money = (n: number) => `₦${Number(n || 0).toLocaleString("en-NG", { maximumFractionDigits: 0 })}`;

export default function OutstandingPage() {
  const [rows, setRows] = useState<Balance[]>([]); const [customers, setCustomers] = useState<{ id: string; full_name: string; phone?: string | null }[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [q, setQ] = useState(""); const [showForm, setShowForm] = useState(false); const [customerId, setCustomerId] = useState(""); const [name, setName] = useState(""); const [phone, setPhone] = useState(""); const [item, setItem] = useState(""); const [amount, setAmount] = useState(""); const [status, setStatus] = useState<"unpaid" | "paid">("unpaid");
  async function load() { setLoading(true); setError(""); const [balances, people] = await Promise.all([businessOperationsService.getCustomerBalances(), customerService.getCustomers()]); if (balances.error) { setError(balances.error.message); setRows([]); } else setRows((balances.data ?? []) as Balance[]); if (!people.error) setCustomers((people.data ?? []) as { id: string; full_name: string; phone?: string | null }[]); setLoading(false); }
  useEffect(() => { void load(); }, []);
  const filtered = useMemo(() => { const query = q.trim().toLowerCase(); return query ? rows.filter(row => `${row.customer_name} ${row.phone}`.toLowerCase().includes(query)) : rows; }, [rows, q]);
  const total = rows.reduce((sum, row) => sum + Number(row.balance), 0); const visibleTotal = filtered.reduce((sum, row) => sum + Number(row.balance), 0);
  function chooseCustomer(id: string) { setCustomerId(id); const person = customers.find(c => c.id === id); if (person) { setName(person.full_name); setPhone(person.phone || ""); } }
  async function submit(event: FormEvent) { event.preventDefault(); const value = Number(amount); if (!name.trim() || !phone.trim() || !item.trim() || value <= 0) { toast.error("Name, phone, item and amount are required."); return; } setSaving(true); const customer = await customerService.addCustomer({ full_name: name.trim(), phone: phone.trim(), email: null, address: null }); if (customer.error || !customer.data?.id) { toast.error(customer.error?.message || "Could not save person."); setSaving(false); return; } const id = String(customer.data.id); const invoice = await businessOperationsService.createInvoiceWithItem({ invoiceNumber: `DB-${Date.now()}`, customerId: id, subtotal: value, total: value, description: item.trim(), quantity: 1, unitPrice: value }); if (invoice.error) { toast.error(invoice.error.message); setSaving(false); return; } if (status === "paid") { const invoiceId = String((invoice.data as { id?: string } | null)?.id || (Array.isArray(invoice.data) ? (invoice.data[0] as { id?: string })?.id : "")); if (invoiceId) { const payment = await businessOperationsService.recordInvoicePayment({ invoiceId, amount: value, paymentMethod: "cash", notes: "Paid at time of debit entry" }); if (payment.error) toast.error(payment.error.message); } } toast.success(status === "paid" ? "Debit recorded as paid." : "Debit recorded."); setShowForm(false); setCustomerId(""); setName(""); setPhone(""); setItem(""); setAmount(""); setStatus("unpaid"); setSaving(false); void load(); }
  function remind(row: Balance) { if (!row.phone) return toast.error("This person has no phone number."); if (!openWhatsApp(row.phone, customerBalanceMessage(row.customer_name, row.balance))) toast.error("Unable to open WhatsApp."); }

  return <AppLayout><main className="space-y-6">
    <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#8a641d]">Daily debit book</p><h1 className="mt-1 font-heading text-3xl font-bold tracking-tight text-[#182a28]">People Who Owe Us</h1><p className="mt-1 max-w-2xl text-sm leading-6 text-[#74837e]">Record it the way the book is written: <strong>name → item collected → price → paid or not paid.</strong> Phone number is kept for statements and reminders.</p></div><button type="button" onClick={() => setShowForm(true)} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-[#123b34] px-5 text-sm font-bold text-white"><Plus className="size-4" /> Record debit</button></header>
    <section className="grid gap-3 sm:grid-cols-3"><Stat label="People owing" value={String(rows.length)} /><Stat label="Total outstanding" value={money(total)} tone="amber" /><Stat label="Showing" value={money(visibleTotal)} /></section>
    {showForm && <section className="rounded-2xl border border-[#d7a95a]/40 bg-[#fffaf0] p-5 shadow-[0_12px_32px_rgba(18,59,52,0.07)]"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#8a641d]">New entry</p><h2 className="mt-1 font-heading text-lg font-bold text-[#182a28]">Record something collected</h2></div><button type="button" onClick={() => setShowForm(false)} className="rounded-lg p-2 text-[#74837e] hover:bg-white"><X className="size-4" /></button></div><form onSubmit={submit} className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-6"><label className="text-xs font-bold text-[#53635d] xl:col-span-2">Existing person<select value={customerId} onChange={e => chooseCustomer(e.target.value)} className="mt-1 h-11 w-full rounded-xl border border-[#dfe6df] bg-white px-3 text-sm font-normal"><option value="">New / choose person</option>{customers.map(c => <option key={c.id} value={c.id}>{c.full_name}{c.phone ? ` · ${c.phone}` : ""}</option>)}</select></label><label className="text-xs font-bold text-[#53635d]">Name<input value={name} onChange={e => setName(e.target.value)} className="mt-1 h-11 w-full rounded-xl border border-[#dfe6df] bg-white px-3 text-sm font-normal" placeholder="Person name" /></label><label className="text-xs font-bold text-[#53635d]">Phone / WhatsApp<input value={phone} onChange={e => setPhone(e.target.value)} className="mt-1 h-11 w-full rounded-xl border border-[#dfe6df] bg-white px-3 text-sm font-normal" placeholder="080..." /></label><label className="text-xs font-bold text-[#53635d] xl:col-span-2">Item collected<input value={item} onChange={e => setItem(e.target.value)} className="mt-1 h-11 w-full rounded-xl border border-[#dfe6df] bg-white px-3 text-sm font-normal" placeholder="e.g. 2 chargers" /></label><label className="text-xs font-bold text-[#53635d]">Price<input type="number" min="1" value={amount} onChange={e => setAmount(e.target.value)} className="mt-1 h-11 w-full rounded-xl border border-[#dfe6df] bg-white px-3 text-sm font-normal" placeholder="₦0" /></label><label className="text-xs font-bold text-[#53635d]">Status<select value={status} onChange={e => setStatus(e.target.value as typeof status)} className="mt-1 h-11 w-full rounded-xl border border-[#dfe6df] bg-white px-3 text-sm font-normal"><option value="unpaid">Not paid</option><option value="paid">Paid</option></select></label><div className="flex items-end md:col-span-2 xl:col-span-2"><button disabled={saving} className="h-11 w-full rounded-xl bg-[#123b34] text-sm font-bold text-white disabled:opacity-50">{saving ? "Saving..." : "Save debit entry"}</button></div></form></section>}
    {error && <div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
    <section className="overflow-hidden rounded-2xl border border-[#dfe6df] bg-white shadow-[0_10px_28px_rgba(18,59,52,0.06)]"><div className="flex flex-col gap-3 border-b border-[#edf0ed] p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-heading text-lg font-bold text-[#182a28]">Outstanding people</h2><p className="mt-1 text-xs text-[#74837e]">Weekly and monthly statements can be sent from each person's record.</p></div><div className="relative w-full sm:w-72"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-[#9aa9a4]" /><input value={q} onChange={e => setQ(e.target.value)} placeholder="Search name or phone" className="h-10 w-full rounded-xl border border-[#dfe6df] pl-9 pr-3 text-sm outline-none focus:border-[#1d6a54]" /></div></div>{loading ? <div className="space-y-3 p-8"><div className="h-12 animate-pulse rounded-xl bg-[#f0f3f0]" /><div className="h-12 animate-pulse rounded-xl bg-[#f0f3f0]" /></div> : filtered.length === 0 ? <div className="p-12 text-center"><HandCoins className="mx-auto size-8 text-[#b6c2bd]" /><p className="mt-3 text-sm font-semibold text-[#394b45]">{q ? "No match." : "Nobody currently owes Danchrista."}</p></div> : <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left"><thead className="bg-[#f7f8f5]"><tr><th className="px-5 py-3 text-[10px] font-bold uppercase tracking-wide text-[#74837e]">Person</th><th className="px-5 py-3 text-[10px] font-bold uppercase tracking-wide text-[#74837e]">Charged</th><th className="px-5 py-3 text-[10px] font-bold uppercase tracking-wide text-[#74837e]">Paid</th><th className="px-5 py-3 text-[10px] font-bold uppercase tracking-wide text-[#74837e]">Balance</th><th className="px-5 py-3 text-[10px] font-bold uppercase tracking-wide text-[#74837e]">Reminder</th><th /></tr></thead><tbody>{filtered.map(row => <tr key={row.customer_id} className="border-t border-[#edf0ed] hover:bg-[#fbfcfa]"><td className="px-5 py-4"><p className="font-semibold text-[#182a28]">{row.customer_name}</p><p className="mt-0.5 text-xs text-[#74837e]">{row.phone || "No phone"}</p></td><td className="px-5 py-4 text-sm">{money(row.debit)}</td><td className="px-5 py-4 text-sm text-emerald-700">{money(row.credit)}</td><td className="px-5 py-4 text-sm font-bold text-amber-700">{money(row.balance)}</td><td className="px-5 py-4"><button type="button" onClick={() => remind(row)} disabled={!row.phone} className="inline-flex items-center gap-1.5 rounded-lg bg-[#eef4f1] px-3 py-2 text-xs font-bold text-[#1d6a54] disabled:opacity-40"><MessageCircle className="size-3.5" /> WhatsApp</button></td><td className="px-5 py-4"><Link href={`/customers/${row.customer_id}`} className="text-xs font-bold text-[#1d6a54]">Open account →</Link></td></tr>)}</tbody></table></div>}</section>
  </main></AppLayout>;
}
function Stat({ label, value, tone }: { label: string; value: string; tone?: "amber" }) { return <div className="rounded-2xl border border-[#dfe6df] bg-white p-5 shadow-[0_8px_24px_rgba(18,59,52,0.05)]"><p className="text-xs font-semibold text-[#74837e]">{label}</p><p className={`mt-2 font-heading text-2xl font-bold ${tone === "amber" ? "text-amber-700" : "text-[#182a28]"}`}>{value}</p></div>; }
