CREATE OR REPLACE FUNCTION public.create_invoice(p_invoice_number text,p_customer_id uuid DEFAULT NULL::uuid,p_repair_id uuid DEFAULT NULL::uuid,p_sale_id uuid DEFAULT NULL::uuid,p_subtotal numeric DEFAULT 0,p_discount numeric DEFAULT 0,p_total numeric DEFAULT 0,p_due_at timestamp with time zone DEFAULT NULL::timestamp with time zone,p_notes text DEFAULT NULL::text) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$
declare v_id uuid;v_company uuid;v_branch uuid;v_source_total numeric;v_source_customer uuid;
begin
 if auth.uid() is null then raise exception 'Not authenticated'; end if; if not public.has_permission('payments.manage') then raise exception 'Permission denied'; end if; v_company:=public.get_my_company_id(); if v_company is null then raise exception 'Company not found'; end if;
 if trim(coalesce(p_invoice_number,''))='' then raise exception 'Invoice number is required'; end if; if p_subtotal<0 or p_discount<0 or p_total<0 or p_discount>p_subtotal then raise exception 'Invalid invoice amounts'; end if; if round(p_total,2)<>round(p_subtotal-p_discount,2) then raise exception 'Invoice total must equal subtotal minus discount'; end if; if p_repair_id is not null and p_sale_id is not null then raise exception 'Invoice cannot be linked to both a repair and a sale'; end if;
 if p_customer_id is not null and not exists(select 1 from public.customers where id=p_customer_id and company_id=v_company) then raise exception 'Customer not found'; end if;
 if p_repair_id is not null then
  select r.branch_id,d.customer_id,greatest(coalesce(r.final_cost,r.estimated_cost,0),0) into v_branch,v_source_customer,v_source_total from public.repairs r join public.devices d on d.id=r.device_id where r.id=p_repair_id and r.company_id=v_company;
  if not found then raise exception 'Repair not found'; end if; if v_source_customer is not null and p_customer_id is distinct from v_source_customer then raise exception 'Linked repair invoice customer must match the repair customer'; end if; if round(p_total,2)<>round(v_source_total,2) then raise exception 'Linked repair invoice total must equal the repair charge'; end if;
 elsif p_sale_id is not null then
  select s.branch_id,s.customer_id,greatest(coalesce(s.total,0),0) into v_branch,v_source_customer,v_source_total from public.sales s where s.id=p_sale_id and s.company_id=v_company; if not found then raise exception 'Sale not found'; end if; if v_source_customer is not null and p_customer_id is distinct from v_source_customer then raise exception 'Linked sale invoice customer must match the sale customer'; end if; if round(p_total,2)<>round(v_source_total,2) then raise exception 'Linked sale invoice total must equal the sale total'; end if;
 end if;
 if v_branch is not null and not public.user_has_branch_access(v_branch) then raise exception 'Branch access denied'; end if;
 insert into public.invoices(company_id,branch_id,customer_id,repair_id,sale_id,invoice_number,subtotal,discount,total,due_at,notes,created_by) values(v_company,v_branch,coalesce(p_customer_id,v_source_customer),p_repair_id,p_sale_id,trim(p_invoice_number),p_subtotal,p_discount,p_total,p_due_at,p_notes,auth.uid()) returning id into v_id;
 if coalesce(p_customer_id,v_source_customer) is not null and p_total>0 and p_repair_id is null and p_sale_id is null then perform public.record_customer_debt(coalesce(p_customer_id,v_source_customer),'invoice',v_id,p_total,0,v_id,v_branch,'Invoice issued'); end if;
 return v_id;
end; $function$;

CREATE OR REPLACE FUNCTION public.create_invoice_with_item(p_invoice_number text,p_customer_id uuid DEFAULT NULL::uuid,p_repair_id uuid DEFAULT NULL::uuid,p_sale_id uuid DEFAULT NULL::uuid,p_subtotal numeric DEFAULT 0,p_discount numeric DEFAULT 0,p_total numeric DEFAULT 0,p_due_at timestamp with time zone DEFAULT NULL::timestamp with time zone,p_notes text DEFAULT NULL::text,p_description text DEFAULT 'Repair / service'::text,p_quantity numeric DEFAULT 1,p_unit_price numeric DEFAULT 0) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$
declare v_id uuid;v_company uuid;v_branch uuid;v_line_total numeric;v_source_total numeric;v_source_customer uuid;v_customer_id uuid;
begin
 if auth.uid() is null then raise exception 'Not authenticated'; end if; if not public.has_permission('payments.manage') then raise exception 'Permission denied'; end if; v_company:=public.get_my_company_id(); if v_company is null then raise exception 'Company not found'; end if;
 if trim(coalesce(p_invoice_number,''))='' then raise exception 'Invoice number is required'; end if; if p_quantity<=0 or p_unit_price<0 or trim(coalesce(p_description,''))='' then raise exception 'Invalid invoice item'; end if; v_line_total:=round(p_quantity*p_unit_price,2); if p_subtotal<0 or p_discount<0 or p_total<0 or p_discount>p_subtotal then raise exception 'Invalid invoice amounts'; end if; if round(p_subtotal,2)<>v_line_total then raise exception 'Invoice subtotal must equal subtotal minus item discount'; end if; if round(p_total,2)<>round(p_subtotal-p_discount,2) then raise exception 'Invoice total must equal subtotal minus discount'; end if; if p_repair_id is not null and p_sale_id is not null then raise exception 'Invoice cannot be linked to both a repair and a sale'; end if;
 if p_customer_id is not null and not exists(select 1 from public.customers where id=p_customer_id and company_id=v_company) then raise exception 'Customer not found'; end if;
 if p_repair_id is not null then select r.branch_id,d.customer_id,greatest(coalesce(r.final_cost,r.estimated_cost,0),0) into v_branch,v_source_customer,v_source_total from public.repairs r join public.devices d on d.id=r.device_id where r.id=p_repair_id and r.company_id=v_company; if not found then raise exception 'Repair not found'; end if; if v_source_customer is not null and p_customer_id is distinct from v_source_customer then raise exception 'Linked repair invoice customer must match the repair customer'; end if; if round(p_total,2)<>round(v_source_total,2) then raise exception 'Linked repair invoice total must equal the repair charge'; end if;
 elsif p_sale_id is not null then select s.branch_id,s.customer_id,greatest(coalesce(s.total,0),0) into v_branch,v_source_customer,v_source_total from public.sales s where s.id=p_sale_id and s.company_id=v_company; if not found then raise exception 'Sale not found'; end if; if v_source_customer is not null and p_customer_id is distinct from v_source_customer then raise exception 'Linked sale invoice customer must match the sale customer'; end if; if round(p_total,2)<>round(v_source_total,2) then raise exception 'Linked sale invoice total must equal the sale total'; end if; end if;
 v_customer_id:=coalesce(p_customer_id,v_source_customer); if v_branch is not null and not public.user_has_branch_access(v_branch) then raise exception 'Branch access denied'; end if;
 insert into public.invoices(company_id,branch_id,customer_id,repair_id,sale_id,invoice_number,subtotal,discount,total,due_at,notes,created_by) values(v_company,v_branch,v_customer_id,p_repair_id,p_sale_id,trim(p_invoice_number),p_subtotal,p_discount,p_total,p_due_at,p_notes,auth.uid()) returning id into v_id;
 insert into public.invoice_items(invoice_id,company_id,description,quantity,unit_price) values(v_id,v_company,trim(p_description),p_quantity,p_unit_price);
 if v_customer_id is not null and p_total>0 and p_repair_id is null and p_sale_id is null then perform public.record_customer_debt(v_customer_id,'invoice',v_id,p_total,0,v_id,v_branch,'Invoice issued'); end if; return v_id;
end; $function$;
